### ISSUE TITLE
Action does not fail if PKGBUILD was not found

### ISSUE THREAD

**Issue by hnicke** [datakrama/archlinux-package-action#1]
The action does not fail if the PKGBUILD was not found.
In my case I ended up not updating the source hashes and still pushing the package to the aur.

You might consider putting `set -e` at the beginning of the script.

**Comment by hapakaien** [comment]
Oh sorry, I forgot. Like this right?

https://github.com/datakrama/archlinux-package-action/blob/54649a2e6b0a480b7dc7043aae56aa094b3d6e31/entrypoint.sh#L2

**Comment by hnicke** [comment]
Yes, exactly. Thank you!
